log:
  exp_name: 'table_wine_all_MLP_4_density_nopose_init'
  save_interval: 1000
guide:
  sjc: True
  text: 'Glasses of wine, salad and french bread on a wooden table.'
  node_text_list: ['Glasses of wine', 'salad', 'french bread', 'wooden table']
  node_pos_list: []
  node_dim_list: []
  box_scale: 0.6
  num_layers: 4
  use_global_density: True
  use_cond_sublatent: False
  use_learnable_pos_dim: True 
  # global_weight: 1e-1
  use_hyper_params: True
optim:
  iters: 8000
  local_iters: 0 # 0
  lambda_global: 100
  lambda_local: 100
  resume: True
  lr: 1e-3
render:
  nerf_type: 'latent'
  density_thresh: 10
  density_init: 5e-1
#  render in high resolution
  eval_w: 128
  eval_h: 128