log:
  exp_name: 'bed_room'
  save_interval: 1000
guide:
  sjc: True
  text: 'A bed is next to a nightstands where a table lamp on it in a room'
  node_text_list: ['a bed', 'a nightstands', 'a table lamp']
  node_pos_list: [[0.0, 0.0, -0.1], [-0.4, -0.2, -0.1], [-0.4, -0.2, 0.1]]
  node_dim_list: [[0.4, 0.86, 0.32], [0.32, 0.32, 0.32], [0.2, 0.2, 0.4]]
  box_scale: 0.7
  num_layers: 6
optim:
  iters: 12000
  local_iters: 0
  lambda_global: 100
  lambda_local: 100
  resume: True
  lr: 1e-3
render:
  nerf_type: 'latent'
  density_thresh: 10
  density_init: 5e-1