log:
  exp_name: 'boy_bike_mlp4'
  save_interval: 1000
  # eval_only: True
guide:
  sjc: True
  text: 'The boy was gleefully riding his bike down the hill, feeling the wind rush past his face.'
  node_text_list: ['a boy', 'a bike', 'hill']
  node_pos_list: [[0.0, -0.0655, -0.26059], [0, 0, 0], [0, 0, -1.0679]]
  node_dim_list: [[0.654, 0.591, 1.232], [0.654, 0.926, 1.0], [0.942, 1.219, 0.281]]
  box_scale: 0.6
  num_layers: 4
optim:
  # ckpt: '/home/data/haotianbai/workdir/CompoNeRF/experiments/bed_room/checkpoints/step_005000.pth'
  iters: 8000
  lambda_global: 50
  lambda_local: 100
  resume: True
  lr: 1e-3
render:
  nerf_type: 'latent'
  density_thresh: 10
  density_init: 5e-1
  test_box_scale: 0.5