log:
  exp_name: 'wristwatch_csdV1.5'
  save_interval: 1000
  # eval_only: True
guide:
  # sjc: True
  csd: True
  text: 'A silvery wristwatch lay on a velvet cloth, its glossy surface reflecting the soft glow of a nearby candle, creating a dance of light and shadow.'
  node_text_list: ['silvery wristwatch', 'velvet cloth', 'candle']
  node_pos_list: [[0, 0, 0], [0, 0, -0.903], [-2.0, 0, 0]]
  node_dim_list: [[1.0, 1.0, 1.0], [1.5, 1.5, 0.5], [0.4, 0.5, 1.5]]
  # box_scale: 0.6 # 0.7
  num_layers: 4
  diffusion_name: 'CompVis/stable-diffusion-v1-5'
optim:
  iters: 10000
  lambda_global: 50
  lambda_local: 100
  resume: True
  lr: 1e-3
render:
  nerf_type: 'latent'
  density_thresh: 10
  density_init: 5e-1
  test_box_scale: 0.5